version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: nclcloudcomputing/javabenchmarkapp
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.3"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet

  mongo:
    image: 'mongo'
    ports:
      - '3306:27017'
    networks:
      - webnet


  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "88:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

networks:
  webnet:

